// Student Profile
let studentName = "Sajan Kumar";
let studentAge = 23;
let studentWeight = 68.5;
let studentHeight = 172;
let studentCity = "Kolkata";
const studentCountry = "India";
let studentCollege = "B. P. Poddar Institute of Management and Technology";
let graduationYear = 2028;
let branch = "Information Technology";
let rollNumber = 11500224020;
let favouriteLanguage = "JavaScript";
let favouriteApp = "WhatsApp";
let dreamCompany = "Google";
let hasLaptop = true;
let isPlaced = false;
let phoneNumber = null;
// Print Values
console.log("Name:", studentName);
console.log("Age:", studentAge);
console.log("Weight:", studentWeight);
console.log("Height:", studentHeight);
console.log("City:", studentCity);
console.log("Country:", studentCountry);
console.log("College:", studentCollege);
console.log("Graduation Year:", graduationYear);
console.log("Branch:", branch);
console.log("Roll Number:", rollNumber);
console.log("Favourite Language:", favouriteLanguage);
console.log("Favourite App:", favouriteApp);
console.log("Dream Company:", dreamCompany);
console.log("Has Laptop:", hasLaptop);
console.log("Is Placed:", isPlaced);
console.log("Phone Number:", phoneNumber);
// Print Datatypes
console.log("Datatype of Name:", typeof studentName);
console.log("Datatype of Age:", typeof studentAge);
console.log("Datatype of Weight:", typeof studentWeight);
console.log("Datatype of Height:", typeof studentHeight);
console.log("Datatype of City:", typeof studentCity);
console.log("Datatype of Country:", typeof studentCountry);
console.log("Datatype of College:", typeof studentCollege);
console.log("Datatype of Graduation Year:", typeof graduationYear);
console.log("Datatype of Branch:", typeof branch);
console.log("Datatype of Roll Number:", typeof rollNumber);
console.log("Datatype of Favourite Language:", typeof favouriteLanguage);
console.log("Datatype of Favourite App:", typeof favouriteApp);
console.log("Datatype of Dream Company:", typeof dreamCompany);
console.log("Datatype of Has Laptop:", typeof hasLaptop);
console.log("Datatype of Is Placed:", typeof isPlaced);
console.log("Datatype of Phone Number:", typeof phoneNumber);